services:
  - type: web
    name: tds-llm-backend
    env: python
    region: singapore
    buildCommand: "pip install -r requirements.txt && playwright install chromium"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port $PORT"
    plan: free
    envVars:
      - key: PLAYWRIGHT_BROWSERS_PATH
        value: /opt/render/.cache/ms-playwright
      - key: GEMINI_API_KEY
        sync: false
      - key: STUDENT_EMAIL
        sync: false
      - key: STUDENT_SECRET
        sync: false
